version: '3.7'
services:
        mongo:
                image: mongo
                volumes:
                     - type: volume
                       source: mongodata
                       target: /data/db
        mongo-service:
                image: michealbmullin/projmongo
                build: ./mongo-service
                depends_on:
                         - mongo
        secret-service:
                image: michealbmullin/projsec
                build: ./secret-service
                depends_on:
                        - mongo-service
        email-service:
                image: michealbmullin/projemail
                build: ./email-service
                depends_on:
                         - mongo-service
                         - aes-encryption-service
                env_file:
                       - ~/email-variables.env
        session-token-service:
                image: michealbmullin/projsession
                build: ./session-token-service
                depends_on:
                        - mongo-service
                        - aes-encryption-service
        aes-encryption-service:
                image: michealbmullin/projaesencrypt
                build: ./aes-encryption-service
        account-service:
                image: michealbmullin/pojaccount
                build: ./account-service
                depends_on:
                         - secret-service
        dashboard-service:
                image: michealbmullin/projdashboardserv
                build: ./dashboard-service
                depends_on:
                         - account-service
                         - session-token-service
        authentication-service:
               image: michealbmullin/projauthenserv
               build: ./authentication-service
               depends_on:
                        - account-service
                        - email-service
                        - session-token-service
        dashboard-client:
               image: michealbmullin/projdashboardcli
               build: ./dashboard-client
        authentication-client:
               image: michealbmullin/projauthenticationcli
               build: ./authentication-client
        gateway:
               image: michealbmullin/projgateway
               build: ./gateway
               ports:
                   - target: 80
                     published: 80
               depends_on:
                        - dashboard-client
                        - authentication-client
                        - authentication-service            
volumes:
        mongodata:
