version: '3.7'
services:
        mongo:
                image: mongo
                volumes:
                     - type: volume
                       source: mongodata
                       target: /data/db
        mongo-service:
                image: michealbmullin/proj/mongoservice
                build: ./mongo-service
                ports:
                    - target: 3000
                depends_on:
                         - mongo
        secret-service:
                image: michealbmullin/proj/secretservice
                build: ./secret-service
                ports:
                    - target: 3000
                depends_on:
                        - mongo-service
volumes:
        mongodata:
